### ISSUE TITLE
Please release a Win64 binary of FFMPEG-AMF, just like what Nvidia did with NvEnc

### ISSUE THREAD

**Issue by wokmi** [Xaymar/ffmpeg-amf#2] opened 2017-11-18 23:45 UTC
Please release a windows64 binary of FFMPEG with AMD AMF/VCE support, just like what Nvidia did with NvEnc. and ASAP.
Hi AMD fellows. 
I have been use "hevc_nvenc" with FFMPEG to encode video for years...to my knowleadge Nvidia've spent a major effort to make their NvENC embeded in the FFMPEG windows builds. But what's with AMD ?  There's even no official website to showcase AMF/VCE..
Recently I chose a RX550 card over GT1030 because the later doesn't support NvENC, and also I'd like to try out the VCE..but what I find out is that even after 3 years VCE still remains in raw source code..
yes, people like me can compile ffmpeg from the source code , but it'd take a couple of days to re-learn the process, and more to maintain the build up-to-day or doing debug..

best regards.

**Comment by MikhailAMD** [comment] 2017-11-19 19:19
We are waiting for code review and final acceptance from ffmpeg team. Check dev forum for October and November.

**Comment by steelbrain** [comment] 2017-11-19 19:32
While I think the request is valid but isn't this a duplicate of #1? Couldn't this issue have been a comment there?

Cheers

**Comment by MikhailAMD** [comment] 2017-11-28 23:17
see issue #1

**Closed as completed** 2017-11-29 08:08 UTC
Labels: duplicate
